/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vintage_pc.glb 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/commodore-64-computer-full-pack-1f43612fa2d54041bbe2bdff8164c2cd
Title: Commodore 64 || Computer (Full Pack)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vintage_pc.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.258, 0.195, 2.2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.computer_details} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.computer_keyboard} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.computer_main_body} />
      </group>
      <group position={[0.542, -0.111, -4.23]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.cable} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.connector} />
      </group>
      <group position={[0, 0.368, -2.43]}>
        <mesh geometry={nodes.Object_17.geometry} material={materials.monitor_black} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.monitor_white} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.monitor_screen} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.monitor_white} position={[1.265, -0.148, 2.24]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.Object_8.geometry} material={materials.peripherals} position={[3.182, 0.071, -2.601]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.peripherals} position={[4.297, 0.478, 1.302]} rotation={[0, 0.602, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.peripherals} position={[-4.423, 1.212, -1.111]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.monitor_plug} position={[0.003, 2.252, -2.083]} />
    </group>
  )
}

useGLTF.preload('/vintage_pc.glb')
