/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vintage_pc.glb 
Author: SeverDoes3D (https://sketchfab.com/SeverDoes3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-assets-16c1a779bb0a4055a26367741d39e059
Title: Office - Assets
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/vintage_pc.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.051, 0.743, 0.876]} rotation={[0, -0.736, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.M_Cactus_1024} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.M_Cactus_1024} position={[0.01, 0.122, 0.014]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.M_Cactus_1024} position={[0.001, 0.123, -0.001]} />
      </group>
      <group position={[-0.235, 1.321, 2.261]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.381}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.433, 0.031, -0.442]} rotation={[-0.02, -0.022, 0]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.441, 0.037, 0.073]} rotation={[-0.032, 0.035, 0]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.117, 0.031, -0.374]} rotation={[-0.047, -0.054, 0.003]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.443, 0.03, 0.199]} rotation={[-0.068, 0.063, 0.004]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.583, 0.03, -0.495]} rotation={[-0.034, -0.059, -0.003]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.192, 0.038, -0.433]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.591, 0.04, -0.475]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.683, 0.043, -0.418]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.437, 0.044, 0.092]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.483, 0.038, 0.226]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.116, 0.037, -0.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
      </group>
      <group position={[0.035, 0.743, 1.904]} rotation={[-Math.PI, 1.358, -Math.PI]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.M_TapeRecorder_1024} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} />
      </group>
      <group position={[-0.22, 2.009, 2.101]}>
        <group position={[0.048, -0.008, 0]}>
          <mesh geometry={nodes.Object_77.geometry} material={materials.M_Vent_1024} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.M_Vent_1024} rotation={[Math.PI / 3, 0, 0]} />
        </group>
        <group position={[0.133, 0.004, 0]}>
          <group position={[-0.159, -0.004, 0]}>
            <mesh geometry={nodes.Object_89.geometry} material={materials.M_Vent_1024} />
            <mesh geometry={nodes.Object_91.geometry} material={materials.M_Vent_1024} position={[0.01, 0.006, 0]} />
            <mesh geometry={nodes.Object_93.geometry} material={materials.M_Vent_1024} position={[0.13, -0.019, 0.186]} />
          </group>
          <mesh geometry={nodes.Object_85.geometry} material={materials.M_Vent_1024} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.M_Vent_1024} position={[0, -0.114, 0]} />
        </group>
        <mesh geometry={nodes.Object_75.geometry} material={materials.M_Vent_1024} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.M_Vent_1024} position={[-0.004, 0.157, 0.238]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.M_Vent_1024} position={[-0.01, 0, 0]} />
      </group>
      <group position={[0.996, 0.565, 0.619]} rotation={[-3.126, -1.002, -1.576]}>
        <mesh geometry={nodes.Object_101.geometry} material={materials.M_Clipboard_Notepad_1024} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.006, -0.034, 0.001]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.381} />
      </group>
      <group position={[-0.039, 0.743, 1.563]} rotation={[0, 0.454, 0]}>
        <group position={[0, 0.061, 0]} rotation={[0, 0, 0.811]}>
          <group position={[0, 0.118, 0]} rotation={[0, 0, -0.976]}>
            <group position={[0, 0.279, 0]} rotation={[0, 0, -0.491]}>
              <group position={[0, 0.366, 0]} rotation={[0, 0, -0.603]}>
                <mesh geometry={nodes.Object_117.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
                <mesh geometry={nodes.Object_119.geometry} material={materials['M_Lamps_CCTV_2048.001']} position={[0, 0.083, 0]} />
              </group>
              <mesh geometry={nodes.Object_115.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
            </group>
            <mesh geometry={nodes.Object_113.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
          </group>
          <mesh geometry={nodes.Object_111.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
        </group>
        <mesh geometry={nodes.Object_109.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
      </group>
      <mesh geometry={nodes.Object_10.geometry} material={materials.M_Computer_2048} position={[0.488, 0.743, 0.925]} rotation={[0, 0.168, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.M_Computer_2048} position={[0.533, 0.743, 0.53]} rotation={[0, -0.169, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.M_Computer_2048} position={[0.061, 0.743, 0.472]} rotation={[0, -0.387, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.M_Computer_2048} position={[0.103, 0.91, 0.502]} rotation={[0, -0.269, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.M_Filebox_1024} position={[-0.084, 0.743, 1.283]} rotation={[0, 1.531, 0]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.M_Filebox_1024} position={[-0.075, 0.743, 1.398]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.M_Filebox_1024} position={[-0.084, 0.743, 1.281]} rotation={[0, 1.531, 0]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.M_Filebox_1024} position={[-0.075, 0.743, 1.398]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[1.096, 1, 1]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.363, 0.743, 1.741]} rotation={[-0.005, 1.388, 0.005]} scale={[0.381, 0.137, 0.381]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.034, 0.743, 1.116]} rotation={[Math.PI / 2, 0, -1.814]} scale={0.381} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.M_Sigarettes_512} position={[0.481, 0.747, 1.504]} rotation={[1.002, 0.422, 0.998]} scale={0.5} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.M_Sigarettes_512} position={[0.382, 0.752, 1.511]} rotation={[Math.PI, -1.189, -1.886]} scale={0.5} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.M_Sigarettes_512} position={[0.487, 0.743, 1.35]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.M_Sigarettes_512} position={[0.446, 0.764, 1.309]} rotation={[-1.448, -0.189, -2.328]} scale={0.5} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.M_Sigarettes_512} position={[0.53, 0.766, 1.406]} rotation={[-1.697, -0.143, 0.343]} scale={0.5} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.M_Sigarettes_512} position={[0.487, 0.752, 1.35]} scale={[1, 0.45, 1]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.M_Sigarettes_512} position={[0.451, 0.752, 1.464]} rotation={[0, -0.571, 1.574]} scale={0.5} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.M_Table_2048} position={[0.213, 0.006, 1.171]} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} position={[0.445, 0.743, 1.958]} rotation={[0, 0.361, 0]} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.Poster_1024} position={[-0.246, 1.568, 1.317]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.619, 0.309, 0.619]} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.PhotoFrame_20x30_likeA4_512} position={[-0.241, 1.27, -0.097]} rotation={[0, -Math.PI / 2, 0]} scale={[0.992, 0.992, 1.118]} />
      <mesh geometry={nodes.Object_99.geometry} material={materials.PhotoFrame_20x30_likeA4_512} position={[-0.241, 1.628, 0.369]} rotation={[0, -Math.PI / 2, 0]} scale={[0.992, 0.992, 1.118]} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.235, 0.743, 1.171]} rotation={[0, 0.319, Math.PI / 2]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.M_OfficeStool_Bin_2048} position={[0.923, 0.008, 0.77]} rotation={[-Math.PI, -0.416, -Math.PI]} scale={[1.235, 1, 1.235]} />
    </group>
  )
}

useGLTF.preload('/vintage_pc.glb')
